# Generated by Django 4.2.1 on 2023-06-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=60)),
                ('name_ru', models.CharField(max_length=60)),
                ('url', models.URLField(blank=True, null=True)),
                ('ad_photo', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=120)),
                ('name_ru', models.CharField(max_length=120)),
                ('category_photo', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='DutyArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=60)),
                ('name_ru', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=30)),
                ('site_url', models.URLField(blank=True, null=True)),
                ('telegram_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('image1', models.ImageField(upload_to='media')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Leading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=60)),
                ('name_ru', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=30)),
                ('site_url', models.URLField(blank=True, null=True)),
                ('telegram_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('image1', models.ImageField(upload_to='media')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=60)),
                ('name_ru', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=30)),
                ('site_url', models.URLField(blank=True, null=True)),
                ('telegram_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('image1', models.ImageField(upload_to='media')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=60)),
                ('name_ru', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=30)),
                ('site_url', models.URLField(blank=True, null=True)),
                ('telegram_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('image1', models.ImageField(upload_to='media')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=60)),
                ('name_ru', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=30)),
                ('site_url', models.URLField(blank=True, null=True)),
                ('telegram_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('star_image1', models.ImageField(upload_to='media')),
                ('star_image2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('star_image3', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name_uz', models.CharField(max_length=120)),
                ('card_name_ru', models.CharField(max_length=120)),
                ('card_desc_uz', models.TextField(max_length=250)),
                ('card_desc_ru', models.TextField(max_length=250)),
                ('card_number', models.CharField(max_length=30)),
                ('card_site_link', models.URLField(blank=True, max_length=120, null=True)),
                ('card_telegram_link', models.URLField(blank=True, max_length=120, null=True)),
                ('card_instagram_link', models.URLField(blank=True, max_length=120, null=True)),
                ('is_top', models.BooleanField(default=False)),
                ('logo', models.ImageField(upload_to='media')),
                ('card_image1', models.ImageField(upload_to='media')),
                ('card_image2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('card_image3', models.ImageField(blank=True, null=True, upload_to='media')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toy_app.category')),
            ],
        ),
    ]
