# Generated by Django 4.2.2 on 2023-06-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_app', '0002_alter_ad_ad_photo_alter_ad_name_ru_alter_ad_name_uz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=60, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=60, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('ad_photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dutyartist',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leading',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='other',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='star',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
